### PR TITLE
Bool matching

### PR DESCRIPTION
**Pull request by gregorybchris**

### CODE REVIEW

**Comment by tekknolagi** [comment]
I don't know if it's worth doing this PR until we reimplement bool as alternatives. @surprisetalk how is that coming along?

**Comment by surprisetalk** [comment]
progress is bad! I just got laid off from work and am scrambling to find work before the holidays hit :(

**Comment by tekknolagi** [comment]
Oh no! I'm sorry to hear that :(

**Comment by gregorybchris** [comment]
Handled in #53

**Pull request closed without merging**
