### PR TITLE
Split parser into main entrypoint and two helpers

### PR DESCRIPTION
**Pull request by neuroevolutus**
`parse` now calls into `parse_expression` and is a bit easier to read.

### CODE REVIEW

**Comment by tekknolagi** [comment]
Ooh, I like that this cleans up the massive function. I wonder about the names. Both functions are parsing expressions and I don't know how name a meaningful difference between the two. The latter feels more cleanly like a `parse_binop`. I would be interested in hearing your thoughts on this. Maybe `parse_unary`? `parse_atom`?

**Comment by tekknolagi** [comment]
Unrelated, I gotta figure out how to turn off preview deploys and building Docker images for others' PRs. Sorry about the red Xes.

**Comment by neuroevolutus** [comment]
> Unrelated, I gotta figure out how to turn off preview deploys and building Docker images for others' PRs. Sorry about the red Xes.

No worries!

**Comment by neuroevolutus** [comment]
> Ooh, I like that this cleans up the massive function. I wonder about the names. Both functions are parsing expressions and I don't know how name a meaningful difference between the two. The latter feels more cleanly like a `parse_binop`. I would be interested in hearing your thoughts on this. Maybe `parse_unary`? `parse_atom`?

I think that `parse_unary` would be a fine name for the new function. `parse_binop` would also be a great choice for renaming the existing `parse` function. Alternatively, since `parse` is responsible for parsing an entire program (as far as I understand), what would you think of renaming it to `parse_program`?

As a side note, I really appreciate how you have a lot of unit tests in the code. It really does make a world of a difference when trying out small refactors such as this.

**Comment by tekknolagi** [comment]
Let's go with `parse_unary` and `parse_binary` and then we can do `parse = parse_binary`. Alternately, we can make `parse` an entirely new function that doesn't take a precedence and then make the precedence non-optional for the other two internal functions. I leave this decision up to you; both are fine with me. After these renames, I would be delighted to merge.

**Comment by tekknolagi** [comment]
Thank you!

**Pull request merged**
